Optilation
vignetteapp/MediaPipe.NET.Runtime pull request #10
Opened 2022-02-22 12:59 UTC by Speykious

A few tweaks for better builds and also a target framework fix.
Previously it targeted both `net6.0` and `netstandard2.1` but I receive a warning on every `net6.0` project because it says that it wasn't made for it for some reason. I think it was due to the `$(TargetFramework)` variable not existing.

2022-02-22 14:00 UTC, sr229 requested changes

2022-02-22 14:21 UTC, Speykious commented on .github/workflows/ci.yml
> +      # - name: Download MacOS build artifacts
There are some undefined symbols that we couldn't solve, so we kinda have to wait until we can properly test MacOS.

2022-02-22 14:26 UTC, sr229 commented on .github/workflows/ci.yml
> +      # - name: Download MacOS build artifacts
I'll set up something for soon but we can leave this be for now.

2022-03-20 14:20 UTC, sr229 approved these changes
We'll figure out how to build this on 2022, for now this looks lit

2022-03-20 14:20 UTC, merged